export const ESCROW_ABI = [
  "constructor(address _corporateWallet, address _municipalWallet)",
  "error AmountRequired()",
  "error DealAlreadyExists()",
  "error DealNotFunded()",
  "error InvalidAddress()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "error TransferFailed()",
  "event EscrowCancelled(string indexed ipfsHash, address indexed depositor, uint256 refundAmount, uint256 timestamp)",
  "event EscrowFunded(string indexed ipfsHash, address indexed depositor, address indexed artist, uint256 amount, uint256 timestamp)",
  "event FiscalRetentionPaid(string indexed ipfsHash, address indexed municipalWallet, uint256 taxAmount, uint256 timestamp)",
  "event FundsReleased(string indexed ipfsHash, address indexed artist, uint256 netAmount, uint256 feeService, uint256 feeTax, uint256 timestamp)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "function BPS_BASE() view returns (uint256)",
  "function SERVICE_FEE_BPS() view returns (uint256)",
  "function TAX_FEE_BPS() view returns (uint256)",
  "function calcularSplit(uint256 _amount) pure returns (uint256 artistAmount, uint256 taxAmount, uint256 serviceAmount)",
  "function cancelarEscrow(string _ipfsHash)",
  "function corporateWallet() view returns (address)",
  "function deals(string) view returns (address depositor, address artist, uint256 amount, uint256 feeService, uint256 feeTax, uint8 status, uint256 createdAt)",
  "function depositarEscrow(address _artist, string _ipfsHash) payable",
  "function getDeal(string _ipfsHash) view returns (tuple(address depositor, address artist, uint256 amount, uint256 feeService, uint256 feeTax, uint8 status, uint256 createdAt))",
  "function liberarPagoEscrow(string _ipfsHash)",
  "function municipalWallet() view returns (address)",
  "function owner() view returns (address)",
  "function renounceOwnership()",
  "function setCorporateWallet(address _newWallet)",
  "function setMunicipalWallet(address _newWallet)",
  "function totalDealsReleased() view returns (uint256)",
  "function totalTaxCollected() view returns (uint256)",
  "function totalVolumeProcessed() view returns (uint256)",
  "function transferOwnership(address newOwner)"
];
